<?php
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$colour_scheme = strtolower($config->getConfigValue(\Vyne\Magento\Helper\Data::VYNE_COLOUR_SCHEME));
if ($config->getConfigValue('payment/vyne/cart_promotion')):
?>
<a href="<?= $block->escapeUrl($block->getCheckoutUrl()) ?>">
    <span class="vyne-banner promo-checkout-<?=$colour_scheme?>"></span>
</a>
<?php
endif;
?>
