<?php
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$colour_scheme = strtolower($config->getConfigValue(\Vyne\Payments\Helper\Data::VYNE_COLOUR_SCHEME)) == 'dark' ? 'dark' : 'light';
$reverse_colour_scheme = $colour_scheme == 'dark' ? 'light' : 'dark';
if ($config->getConfigValue('payment/vyne/pdp_promotion')):
?>
<script>
function showPopup() {
    document.getElementsByClassName('vyne-popup')[0].style.visibility = 'visible';
}
function hidePopup() {
    document.getElementsByClassName('vyne-popup')[0].style.visibility = 'hidden';
}
</script>
<span class="vyne-banner promo-pdp-<?=$colour_scheme?>">
    <span class="promo_logo">
        <img src="<?php echo $this->getViewFileUrl('Vyne_Payments::images/logos/logo-'.$colour_scheme.'-alt1.svg'); ?>" />
        <a data-bind="click: showPopup()"><img style="width: 20px; height:20px; padding-bottom: 5px; margin-right: -10px;" data-bind="attr: { src: require.toUrl('Vyne_Payments/images/logos/info-circle-<?=$reverse_colour_scheme?>.svg') }" alt="info_circle"/></a>
    </span>
    <span class="promo_text_1">
        <?= $block->escapeHtml($config->getConfigValue('payment/vyne/promo_text_1'))?>
    </span>
    <br/>
    <span class="promo_text_2">
        <?= $block->escapeHtml($config->getConfigValue('payment/vyne/promo_text_2'))?>
    </span>
</span>

<div class="vyne-popup" style="visibility: hidden">
    <a class="close" style="cursor: pointer" data-bind="click: hidePopup()">x</a>
    <div class="description">
        <p><img data-bind="attr: { src: require.toUrl('Vyne_Payments/images/popup/vyne2bank.svg') }" alt="vyne2bank"></p>
        <h3>How does it work?</h3>
        <p>Let us know the bank you'd like to pay with, and we'll redirect you to sign in securely - no card details required.</p>
    </div>
    <div class="steps">
        <div class="step1">
            <h5>Select your bank</h5>
            <p>Pay directly in your banking app, no Vyne</p>
        </div>
        <div class="step2">
            <h5>Log into your banking app</h5>
            <p>Vyne will securely connect you to your banking app.</p>
        </div>
        <div class="step3">
            <h5>Approve the connection</h5>
            <p>Approve the payment, and it's as easy as that - checkout complete.</p>
        </div>
    </div>
    <div class="control">
        <a class="button secondary" data-bind="click: hidePopup()">Close</a>
        <a class="button primary" href="https://www.payvyne.com/pay-with-vyne#faqs" target="_blank"><span>More about</span> <img  data-bind="attr: { src: require.toUrl('Vyne_Payments/images/popup/btn_logo.svg') }" alt="Vyne"></a>
        <div style="clear: both"></div>
    </div>
</div>

<?php
endif;
?>
