<?php
echo /* @noEscape */ $block->getChildHtml();

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->escapeJs($block->getBaseUrl()) .'\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->escapeJs($block->getViewFileUrl('/')) . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
